import js from "@eslint/js";
import eslintConfigPrettier from "eslint-config-prettier";
import importPlugin from "eslint-plugin-import";
import reactPlugin from "eslint-plugin-react";
import globals from "globals";

/**
 * This file defines specific rules for Prettier. It adjusts their default settings.
 * We recommend these settings if your lab does not have specific linting standards.
 *
 * @type {import('eslint').FlatConfig}
 */
export default [
  // Global ignores
  {
    ignores: [
      // Dependencies
      "node_modules",

      // Testing
      "coverage",

      // Production
      "build",
      "dist",
      "out",

      // Autogenerated files
      "public/lib/*",
      "**/participant_responses",
      "psiturkit/*_turk",
      "*.log",
      "*.log*",

      // Misc
      ".husky",
      ".vscode",
      ".env",
      ".env",
      ".DS_Store",
      ".gitignore",
      "**/firebase-service-account.json",
    ],
  },

  // Add the base configurations
  js.configs.recommended,
  reactPlugin.configs.flat.recommended,
  importPlugin.flatConfigs.recommended,

  // Custom configuration
  {
    files: ["**/*.{js,jsx}"],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "module",
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.jest,
      },
    },
    rules: {
      "no-unused-vars": "warn",
      "import/order": "warn",
    },
    settings: {
      react: { version: "detect" },
      jsdoc: { tagNamePreference: { typedef: { definedInFiles: ["src/lib/typedef.js"] } } },
      "import/resolver": { node: { extensions: [".js", ".jsx"] } },
    },
  },

  // Prettier config
  // NOTE @RobertGemmaJr: Must be last, prettier should override other configs
  eslintConfigPrettier,
];
