#!/bin/bash
set -e

usage () { echo "Usage: [-h] [-p] [-u]"
           echo "     -h – help"
           echo "     -p – Psiturk directory path"
           echo "     -u – Update existing Psiturk Task"; }


 while getopts p:u option
 do
   case "${option}" in
     p) PSI_PATH=${OPTARG};;
     u)
        echo "Cleaning up old directory"
        rm -rf ${PSI_PATH}
        ;;
     \?) usage; exit;;
   esac
 done


if [ -z ${PSI_PATH+x} ]; then
   echo "Please set the task input and output directories. Use -t for
jsPsych task path and -p for the psiturk output directory. Make sure you have PsiTurk installed."
else
   echo "Setting up ${PSI_PATH} PsiTurk project"
   psiturk-setup-example
   cp -R ../build/static/* psiturk-example/static/
   cp ../build/*.js* psiturk-example/static/
   cp ../build/lib/*.js psiturk-example/static/lib
   cp ../build/index.html psiturk-example/templates/exp.html
   mv psiturk-example ${PSI_PATH}
fi
