name: 🏗️ Pull Request
on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 🧪 Build
    runs-on: ${{ matrix.os }}

    # Run action for [home/clinic] with in [windows/macOS/ubuntu]
    strategy:
      matrix:
        setting: [home, clinic]
        os: [windows-latest, macOS-latest, ubuntu-latest]
      fail-fast: false # A failed build will not end the other matrix jobs

    steps:
      # Set up runner
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm

      # Install dependencies
      - name: 📥 Install Dependencies
        run: npm ci

      # Set up the environment
      - name: 🔃 Load .env file (.env.${{matrix.setting}})
        uses: xom9ikk/dotenv@v2
        with:
          path: ./env
          mode: ${{matrix.setting}}

      # Lint the code
      - name: 🔬 Lint
        run: npm run lint -- --max-warnings=0

      # Build the app
      - name: ⚒ Build
        run: npm run build
