name: 🧪 Test Dispatch

# Workflow dispatch for packaging an electron executable
on:
  workflow_dispatch:
    inputs:
      setting:
        type: choice
        options:
          - "home"
          - "clinic"
        default: "home"
        required: true
        description: Package the app for 'home' or 'clinic' use
      os:
        type: choice
        description: Which operating system to make executables for
        required: true
        default: "All"
        options:
          - "All"
          - "Windows"
          - "macOS"
          - "Linux"

jobs:
  test-dispatch:
    name: Test Dispatch
    runs-on: ${{ matrix.os }}

    # Run action for [home/clinic] in [windows/macOS/ubuntu] based on user input
    strategy:
      matrix:
        # TODO: There's got to be a better way to handle this?
        # os: ${{
        #   (github.event.inputs.os == 'All' && fromJSON('["ubuntu-latest", "macOS-13", "windows-latest"]')) ||
        #   (github.event.inputs.os == 'Windows' && fromJSON('["windows-latest"]')) ||
        #   (github.event.inputs.os == 'macOS' && fromJSON('["macOS-13"]')) ||
        #   (github.event.inputs.os == 'Linux' && fromJSON('["ubuntu-latest"]')) }}
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        exclude:
          - os: ubuntu-latest
            if: ${{ github.event.inputs.os != 'All' && github.event.inputs.os != 'Linux' }}
          - os: macOS-latest
            if: ${{ github.event.inputs.os != 'All' && github.event.inputs.os != 'macOS' }}
          - os: windows-latest
            if: ${{ github.event.inputs.os != 'All' && github.event.inputs.os != 'Windows' }}
      fail-fast: false # A failed build will not end the other matrix jobs

    steps:
      # Set up runner
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - run: echo ${{ runner.os }}
